mysql:
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: go-gin-admin
  log-mode: ""
  log-zap: false
  max-idle-conns: 0
  max-open-conns: 0
  password: "12345678"
  path: 127.0.0.1
  port: "3306"
  username: root

redis:
  addr: 127.0.0.1:6379
  db: 0
  password: ""

system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
